### PR TITLE
asd

### PR DESCRIPTION
**Pull request by Poodleschool**
ad

### CODE REVIEW

**Comment by bcrhbrhcdb** [comment]
How do i deploy this?

**Comment by Poodleschool** [comment]
> How do i deploy this?

You can deploy it to cyclic and tons more

**Comment by bcrhbrhcdb** [comment]
Will vercle work? Netlify? Railway?

**Comment by Poodleschool** [comment]
> Will vercle work? Netlify? Railway?

Vercel works sometimes. Netflify doesn't since it's a static host and says server error when you do it there. We recommend cyclic and hop (required credit card but can make unlimited links and is free)

You can also host pooxie proxy with your vps.

**Comment by Poodleschool** [comment]
> Will vercle work? Netlify? Railway?

Please dm me on discord for any further requests as it will be faster

**Comment by Poodleschool** [comment]
Discord: master_of_pooms

**Pull request merged**
